apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
    - name: jnlp
      image: default-route-openshift-image-registry.apps.shared.na.openshift.opentlc.com/openshift/jenkins-agent-maven
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      tty: false
      resources:
        requests:
          cpu: 200m
          memory: 1024Mi
        limits:
          cpu: 200m
          memory: 1024Mi
